name: Deployment_Release

on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          npm run-script build-prod
          cp robots.txt public/robots.txt
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy -P prod --only hosting:portfolio-panel
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
